
modLoader="javafml" #mandatory

loaderVersion="[34,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="All rights reserved"

issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]] #mandatory

modId="extc" #mandatory

version="1.16.4-2.0.1" #mandatory

displayName="ExtendedCraft" #mandatory

updateJSONURL="http://myurl.me/" #optional

displayURL="https://github.com/KonaB15/ExtendendedCraft" #optional

logoFile="ExtendedCraft.png" #optional

credits="Thanks to FuriousMiner for helping me make some of the textures." #optional

authors="KonaB15" #optional

description='''
2.1 - Fixed some crafting recipes. Added ore generation.
2.0 - Completely re-wrote the crafting system!
'''


# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.examplemod]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[34,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
